### ISSUE TITLE
Some error or in src/ColorizeDataloader function generate_batch

### ISSUE THREAD

**Issue by XiaoluJiayou** [superhighlevel/ChromaGan_Pytorch_Remake#1]
in your code which  is  src/ColorizeDataloader function generate_batch,

filename = os.path.join(self.color_path, self.filelist[self.data_index])  ,this self.data_index  may  a error because it no initialize

**Comment by superhighlevel** [comment]
Thanks for the feedback about the model.
The function generate_batch is an old function and doesn't contribute anything to the model. So no need to worry about it

**Comment by XiaoluJiayou** [comment]
> 感谢您对模型的反馈。 函数 generate_batch 是一个旧函数，对模型没有任何贡献。所以不用担心

Thank you reply.

**Comment by superhighlevel** [comment]
The current model can train now. But there are still a lot of things that can be improved. Hope this project was help you somethings. I will close this post. Thank <3
