### ISSUE TITLE
Quetions about the result

### ISSUE THREAD

**Issue by OHaiYo-lzy** [superhighlevel/ChromaGan_Pytorch_Remake#10]
![0_0](https://user-images.githubusercontent.com/69071726/183237898-60d79489-3550-4cbb-aa7b-ef77cbe65cb2.png)
after training ，my model always gave me gray result althugh the shape of image is (224,224,3).can anyone tell me what wrong with the code?

and I just add those files for training and testing..
![image](https://user-images.githubusercontent.com/69071726/183237984-536b9698-c477-4a77-96a9-1f6efb214ba5.png)

**Comment by superhighlevel** [comment]
Hmm, I'm not sure. After training the model, does it output a weight file? if it does you can use [ProductColorization.py](https://github.com/superhighlevel/ChromaGan_Pytorch_Remake/blob/master/src/ProductColorization.py) to test with gray images. And the training file should be all color, data loader handled the decolor proces

**Comment by OHaiYo-lzy** [comment]
Thanks for your swift reply!But after I used&nbsp;ProductColorization.py&nbsp;to colorize, I still got gray results like








I emailed my .pt file too.Could load that and see if it works?thx !!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "superhighlevel/ChromaGan_Pytorch_Remake"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月6日(星期六) 下午3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [superhighlevel/ChromaGan_Pytorch_Remake] Quetions about the result (Issue #10)





 
Hmm, I'm not sure. After training the model, does it output a weight file? if it does you can use ProductColorization.py to test with gray images. And the training file should be all color, data loader handled the decolor proces
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

colorization.pt (653.00M, 2022年09月05日 15:21 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=22623435253c06e635fa87791e31041e570303050f0206534b5a5550081c0201075a190d5a07521c540357540d540e045f030300383e3652090e5b47514b57450f0d5a1b4845360c&code=fb458161

**Comment by superhighlevel** [comment]
Thanks, I just accidentally checked my email and saw the issue. I think I will maintain the code for more usability since people still use this repo.

**Comment by superhighlevel** [comment]
I just updated the code. Please tell me if there's any error or bug
cc @OHaiYo-lzy

**Comment by OHaiYo-lzy** [comment]
still got gray output..

**Comment by OHaiYo-lzy** [comment]
finally see color!thx!!

by the way I find the reason that I got gray merely ,that is I used .JPEG image rather than .jpg!
Hopefully it  will be handled !

**Comment by OHaiYo-lzy** [comment]
@superhighlevel Encountered another weird circumstance..
When I TRIED ImageNet dataset for train and testing ,I failed to acheive colorful result again...
But when tried your sample dataset ,the code works...
wondering eagerly ..
Can you try to train and test your model on ImageNet?

**Comment by superhighlevel** [comment]
I'm not yet testing this model on ImageNet. Not sure if my GPU can handle the large data but i will try, by the end of this week at the latest

**Comment by OHaiYo-lzy** [comment]
THX for your reply!
But what I wanna say is that I CANNOT train with ImageNet dataset，in fact I can't train on most datasets except your sample data.Hopefully it will be handled!


By the way could you kindly tell me where your sample data from?



---Original---
From: "Lê Văn ***@***.***&gt;
Date: Tue, Aug 9, 2022 17:43 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [superhighlevel/ChromaGan_Pytorch_Remake] Quetions about theresult (Issue #10)




 
I'm not yet testing this model on ImageNet. Not sure if my GPU can handle the large data but i will try, by the end of this week at the latest

**Comment by superhighlevel** [comment]
Indeed, The current model is just a bare bones, I'm not sure it will give the same results as the author. There is still a lot that can be optimized and done. But I can get a model that gives acceptable results on a private dataset, thus, weight cannot be shared.
I get the sample from [food-101-mini](https://www.kaggle.com/datasets/msarmi9/food101tiny)

**Comment by OHaiYo-lzy** [comment]
Thanks for kind help

**Comment by OHaiYo-lzy** [comment]
thx and hopefully the issue be handled！



---Original---
From: "Lê Văn ***@***.***&gt;
Date: Sat, Aug 6, 2022 15:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [superhighlevel/ChromaGan_Pytorch_Remake] Quetions about theresult (Issue #10)




 
Thanks, I just accidentally checked my email and saw the issue. I think I will maintain the code for more usability since people still use this repo.
