### ISSUE TITLE
Exception: The path is not a directory

### ISSUE THREAD

**Issue by XiaoluJiayou** [superhighlevel/ChromaGan_Pytorch_Remake#2]
![image](https://user-images.githubusercontent.com/94163973/164196698-121eeee9-6fe3-47e7-8980-64486b14104b.png)

this path should existing but run could generate error

![image](https://user-images.githubusercontent.com/94163973/164196135-cfab9b89-bc94-4d67-8750-04633e92cdb3.png)

![image](https://user-images.githubusercontent.com/94163973/164196529-88e2f617-01df-48c4-8645-ee198a9d32b4.png)

my terminal code is    python main.py --config configs/config.py --mode 1

**Comment by superhighlevel** [comment]
The 'celeb-dataset' should be 'celeb_dataset'

**Comment by XiaoluJiayou** [comment]
Im so sorry ,thank you reply so much .Could  you give me a private email.we sholud keep a close reaction for this code. thank your help

**Comment by XiaoluJiayou** [comment]
![image](https://user-images.githubusercontent.com/94163973/164214364-c952d8a5-b40f-4dc0-a721-a8f5902ec8f7.png)



In this configs/config.py   the GLR and DLR (generator and discriminator learning rate shuold be initiate.
![image](https://user-images.githubusercontent.com/94163973/164214802-a8786c30-64ff-4382-98fd-91b3fe348c1c.png)
