### ISSUE TITLE
Cannot use gpu acceleration training

### ISSUE THREAD

**Issue by XiaoluJiayou** [superhighlevel/ChromaGan_Pytorch_Remake#3]
![image](https://user-images.githubusercontent.com/94163973/164234074-b86360c8-e17b-4aae-8880-01f72b3ac420.png)

![image](https://user-images.githubusercontent.com/94163973/164234161-4546a0b7-5b9a-49ff-be18-0c12f38d1463.png)

I try to use CUDA_VISIBLE_DEVICES=0 python mian.py --config configs/config.py --mode 1 in terminal 
to acceleration training .But through this code nvidia-smi find that gpu is not use for training

![image](https://user-images.githubusercontent.com/94163973/164235803-b2802bfd-c5cf-4c66-a5c0-77d8eec1eb76.png)

**Comment by superhighlevel** [comment]
I'm not sure what this error is, can you give more details?

**Comment by XiaoluJiayou** [comment]
hello ,this problem is my error,thank you attention.   Thankkkkkkk youuuu
