### ISSUE TITLE
There is a way colud take these images from Imagenet2012 to 224 *224

### ISSUE THREAD

**Issue by XiaoluJiayou** [superhighlevel/ChromaGan_Pytorch_Remake#5]
I find if we add this code in ColorizeDataloader.py  functions transform.compose() ，we could take Imagenet2012 dataset directly input your network.Please take some attention for it.Thank your attention and hope your reply.
![image](https://user-images.githubusercontent.com/94163973/164444875-85293384-1495-4289-a8be-ad6e36a4c717.png)

**Comment by XiaoluJiayou** [comment]
hello,Could you give me a private e-mail .If I have some thinks about improve this code ,we could keep a real-time correspons.Hope your reply,thank you

**Comment by wangxinlei777** [comment]
我们可以联系一下，老哥，2232797012@qq.com

**Comment by superhighlevel** [comment]
> I find if we add this code in ColorizeDataloader.py functions transform.compose() ，we could take Imagenet2012 dataset directly input your network.Please take some attention for it.Thank your attention and hope your reply. ![image](https://user-images.githubusercontent.com/94163973/164444875-85293384-1495-4289-a8be-ad6e36a4c717.png)

Oh really thank,  I thought I was put that code here.
Btw, Levanhieu231@gmail.com is my working email. you can contact Wangxinlei777 - Collaborator with the project, and he is Chinese to.
