### ISSUE TITLE
error for checking_data_loader

### ISSUE THREAD

**Issue by XiaoluJiayou** [superhighlevel/ChromaGan_Pytorch_Remake#6]
![image](https://user-images.githubusercontent.com/94163973/165022600-184504fb-2a8c-46c5-8fec-caacfb4a8bb5.png)
my config.TRAIN_PATH ='D:/train/n01440764/'
![image](https://user-images.githubusercontent.com/94163973/165022642-e4693c69-a5b4-4483-909a-7483dd9c20ab.png)
CHECK DATALOADER
![image](https://user-images.githubusercontent.com/94163973/165022759-79e67a7d-2e6b-4dfc-a66e-b9b59d924111.png)

**Comment by superhighlevel** [comment]
Hmm I think because i messup the resize in transform function. I will fix it ASAP. thank

**Comment by XiaoluJiayou** [comment]
hello,I have a solution for this error.
![image](https://user-images.githubusercontent.com/94163973/165069830-71de72e2-e829-498b-b413-a52164decab1.png)
This error origin the function read_img(), it return four results include grey image, ab image, original image,and original lab image. 
And in __getitem__,transform only use in gray_img and ab_img, not include the original image and original lab image(the two class img not use in after code).
So a batch size are not a same size ,it could generate error.And my solution is drop out these two class images
![image](https://user-images.githubusercontent.com/94163973/165070844-0f2d1fb1-885c-4228-aee0-512d4c95eeab.png)
just return two which are gray and ab_images
![image](https://user-images.githubusercontent.com/94163973/165070877-72e8eb3a-3643-40c3-a014-2d98118d2a54.png)

**Comment by superhighlevel** [comment]
Thank you,
I can see that happen. In the original code of the author, he also returns
4 images, so I do. I guess I will following you to change that.
Thank again,
Hieu

Vào Th 2, 25 thg 4, 2022 vào lúc 17:23 XiaoluJiayou <
***@***.***> đã viết:
