### ISSUE TITLE
error in test

### ISSUE THREAD

**Issue by XiaoluJiayou** [superhighlevel/ChromaGan_Pytorch_Remake#7]
Hello , when I run this code ,could generate a error in trainer.test.
![image](https://user-images.githubusercontent.com/94163973/165519948-b41c46e4-7fde-4218-a7be-8829e80ea754.png)
It may be origined from Dataloader. If the number of dataset could not exact division the batch_size could generate this error.
So,my solution is setting Dataloader( drop_last=True) that could not have this error.
Last but not least, very ,very,very thank your code.It have great help to me.
![image](https://user-images.githubusercontent.com/94163973/165520900-1c3d2972-35a5-4e33-8ecd-66c06365fd17.png)

**Comment by superhighlevel** [comment]
Thank you, hope you enjoyed the model. I just forgot to put that here, fixed.
