### ISSUE TITLE
The two variable not use in next code. what is these variable intention

### ISSUE THREAD

**Issue by XiaoluJiayou** [superhighlevel/ChromaGan_Pytorch_Remake#9]
![image](https://user-images.githubusercontent.com/94163973/175239738-27bee141-e124-4df2-80a4-c27c88446d4c.png)

**Comment by XiaoluJiayou** [comment]
In  src trainer   def Model funcition

**Comment by superhighlevel** [comment]
I think that is for the testing purpose but i forgot to remove it.
I don't think it effect the model since it has no connect to grad.
Can you make a pull request to remove it?
